// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internal/serialize/message.proto

package serializepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Produce struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Produce) Reset() {
	*x = Produce{}
	mi := &file_internal_serialize_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Produce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Produce) ProtoMessage() {}

func (x *Produce) ProtoReflect() protoreflect.Message {
	mi := &file_internal_serialize_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Produce.ProtoReflect.Descriptor instead.
func (*Produce) Descriptor() ([]byte, []int) {
	return file_internal_serialize_message_proto_rawDescGZIP(), []int{0}
}

func (x *Produce) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Consume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Acked         bool                   `protobuf:"varint,3,opt,name=acked,proto3" json:"acked,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Retries       int32                  `protobuf:"varint,5,opt,name=retries,proto3" json:"retries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Consume) Reset() {
	*x = Consume{}
	mi := &file_internal_serialize_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consume) ProtoMessage() {}

func (x *Consume) ProtoReflect() protoreflect.Message {
	mi := &file_internal_serialize_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consume.ProtoReflect.Descriptor instead.
func (*Consume) Descriptor() ([]byte, []int) {
	return file_internal_serialize_message_proto_rawDescGZIP(), []int{1}
}

func (x *Consume) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Consume) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Consume) GetAcked() bool {
	if x != nil {
		return x.Acked
	}
	return false
}

func (x *Consume) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Consume) GetRetries() int32 {
	if x != nil {
		return x.Retries
	}
	return 0
}

var File_internal_serialize_message_proto protoreflect.FileDescriptor

const file_internal_serialize_message_proto_rawDesc = "" +
	"\n" +
	" internal/serialize/message.proto\"#\n" +
	"\aProduce\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x81\x01\n" +
	"\aConsume\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x14\n" +
	"\x05acked\x18\x03 \x01(\bR\x05acked\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x18\n" +
	"\aretries\x18\x05 \x01(\x05R\aretriesB>Z<github.com/suman7383/go-queue/internal/serialize;serializepbb\x06proto3"

var (
	file_internal_serialize_message_proto_rawDescOnce sync.Once
	file_internal_serialize_message_proto_rawDescData []byte
)

func file_internal_serialize_message_proto_rawDescGZIP() []byte {
	file_internal_serialize_message_proto_rawDescOnce.Do(func() {
		file_internal_serialize_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_serialize_message_proto_rawDesc), len(file_internal_serialize_message_proto_rawDesc)))
	})
	return file_internal_serialize_message_proto_rawDescData
}

var file_internal_serialize_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_serialize_message_proto_goTypes = []any{
	(*Produce)(nil), // 0: Produce
	(*Consume)(nil), // 1: Consume
}
var file_internal_serialize_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_serialize_message_proto_init() }
func file_internal_serialize_message_proto_init() {
	if File_internal_serialize_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_serialize_message_proto_rawDesc), len(file_internal_serialize_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_serialize_message_proto_goTypes,
		DependencyIndexes: file_internal_serialize_message_proto_depIdxs,
		MessageInfos:      file_internal_serialize_message_proto_msgTypes,
	}.Build()
	File_internal_serialize_message_proto = out.File
	file_internal_serialize_message_proto_goTypes = nil
	file_internal_serialize_message_proto_depIdxs = nil
}
